### ISSUE TITLE
Store Data-History in PostgreSQL

### ISSUE THREAD

**Issue by dns2utf8** [coredump-ch/spaceapi-server-rs#11]
So we have a "complete" History of the Data.

Maybe this should be solved in the status-Project, so we keep this generic.

**Comment by dbrgn** [comment]
I'm not sure whether data logging should be part of the SpaceAPI server. A more scalable approach would probably be to write a microservice that fetches the API regularly and logs the data to a database (like [status logger](https://github.com/coredump-ch/status-logger) does it).

@dns2utf8 @rnestler opinions?

**Comment by dbrgn** [comment]
@dns2utf8 @rnestler ping? :)

**Comment by dns2utf8** [comment]
the status logger works very good.

Closing for now.
