### ISSUE TITLE
Add internal version information to output

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/spaceapi-server-rs#4]
We could add the version number of the spaceapi crate and of the spaceapi-server crate to a custom field in the output.

For example:

```
{
    ...
    "ext_versions": {
        "spaceapi": "0.1.2",
        "spaceapi_server": "0.2.0",
    }
}
```

**Comment by dns2utf8** [comment]
Each crate chould provide a function to return `env!("CARGO_PKG_VERSION")`

**Comment by dbrgn** [comment]
Implemented:

- https://github.com/coredump-ch/spaceapi-rs/pull/31
- https://github.com/coredump-ch/spaceapi-server-rs/pull/52
